import profile from "../assets/images/profile.png";

export const contracts = [
  {
    id: 1,
    projectTitle: "SaaS dashboard redesign",
    freelancerName: "Ahmed Benali",
    avatar: profile,
    budget: 2400,
    deliverableDeadline: "2026-04-18",
    createdAt: "2026-03-26T09:30:00Z",
    status: "active",
    deliverablePaymentStatus: "in_escrow",
    deliverablesCount: 3,
    completedDelivrables: 2,
  },
  {
    id: 2,
    projectTitle: "Restaurant booking mobile app",
    freelancerName: "Lina Berrada",
    avatar: profile,
    budget: 1850,
    deliverableDeadline: "2026-04-11",
    createdAt: "2026-03-25T14:15:00Z",
    status: "pending",
    deliverablePaymentStatus: "in_escrow",
    deliverablesCount: 2,
    completedDelivrables: 0,
  },
  {
    id: 3,
    projectTitle: "SEO content pipeline",
    freelancerName: "Sara El Idrissi",
    avatar: profile,
    budget: 960,
    deliverableDeadline: "2026-04-06",
    createdAt: "2026-03-21T10:00:00Z",
    status: "completed",
    deliverablePaymentStatus: "paid",
    deliverablesCount: 6,
    completedDelivrables: 3,
  },
  {
    id: 4,
    projectTitle: "E-learning landing page",
    freelancerName: "Omar Tazi",
    avatar: profile,
    budget: 720,
    deliverableDeadline: "2026-04-03",
    createdAt: "2026-03-24T12:45:00Z",
    status: "rejected",
    deliverablePaymentStatus: "unpaid",
    deliverablesCount: 1,
    completedDelivrables: 0,
  },
  {
    id: 5,
    projectTitle: "Marketplace admin panel",
    freelancerName: "Youssef Amrani",
    avatar: profile,
    budget: 3100,
    deliverableDeadline: "2026-05-02",
    createdAt: "2026-03-19T08:20:00Z",
    status: "active",
    deliverablePaymentStatus: "in_escrow",
    deliverablesCount: 4,
    completedDelivrables: 2,
  },
  {
    id: 6,
    projectTitle: "Travel blog UI refresh",
    freelancerName: "Imane Zahra",
    avatar: profile,
    budget: 1280,
    deliverableDeadline: "2026-04-27",
    createdAt: "2026-03-18T16:00:00Z",
    status: "cancelled",
    deliverablePaymentStatus: "unpaid",
    deliverablesCount: 0,
    completedDelivrables: 0,
  },
  {
    id: 7,
    projectTitle: "Fintech onboarding flow",
    freelancerName: "Hamza Naji",
    avatar: profile,
    budget: 2100,
    deliverableDeadline: "2026-04-15",
    createdAt: "2026-03-23T11:10:00Z",
    status: "pending",
    deliverablePaymentStatus: "in_escrow",
    deliverablesCount: 2,
    completedDelivrables: 0,
  },
];
