export const projects = [
  {
    id: 1,
    title: "e-commerce web site",
    description:
      "Build a modern e-commerce platform with product listings, cart functionality, and secure checkout. The system should support user accounts and order tracking.",
    budget: 20,
    createdAt: "2026-03-20",
    status: "completed",
    proposalsCount: 3,
    experienceLevel: "mid",
    projectSize: "medium",
    estimatedDuration: "1_to_3_months",
  },
  {
    id: 2,
    title: "restaurant frontend",
    description:
      "Develop a responsive frontend for a restaurant website including menu display, reservation form, and smooth UI animations.",
    budget: 18,
    createdAt: "2026-03-21",
    status: "open",
    proposalsCount: 2,
    experienceLevel: "junior",
    projectSize: "small",
    estimatedDuration: "less_than_1_month",
  },
  {
    id: 3,
    title: "weather api",
    description:
      "Create a REST API that provides real-time weather data based on location, with caching and error handling for external API requests.",
    budget: 10,
    createdAt: "2026-03-17",
    status: "open",
    proposalsCount: 2,
    experienceLevel: "junior",
    projectSize: "small",
    estimatedDuration: "less_than_1_month",
  },
  {
    id: 4,
    title: "ui/ux design",
    description:
      "Design a clean and intuitive UI/UX for a mobile and web application, including wireframes, prototypes, and design system guidelines.",
    budget: 30,
    createdAt: "2026-03-23",
    status: "open",
    proposalsCount: 1,
    experienceLevel: "mid",
    projectSize: "medium",
    estimatedDuration: "1_to_3_months",
  },
  {
    id: 5,
    title: "e-commerce web site",
    description:
      "Improve an existing e-commerce website by optimizing performance, redesigning product pages, and enhancing user experience.",
    budget: 25,
    createdAt: "2026-03-22",
    status: "in_review",
    proposalsCount: 3,
    experienceLevel: "mid",
    projectSize: "medium",
    estimatedDuration: "1_to_3_months",
  },
  {
    id: 6,
    title: "freelance app",
    description:
      "Develop a freelance marketplace platform with client and freelancer roles, proposal system, messaging, and basic payment workflow.",
    budget: 255,
    createdAt: "2026-01-24",
    status: "cancelled",
    proposalsCount: 0,
    experienceLevel: "senior",
    projectSize: "large",
    estimatedDuration: "3_to_6_months",
  },
  {
    id: 7,
    title: "portfolio",
    description:
      "Create a personal portfolio website showcasing projects, skills, and experience with a modern and responsive design.",
    budget: 100,
    createdAt: "2026-03-24",
    status: "in_review",
    proposalsCount: 1,
    experienceLevel: "junior",
    projectSize: "small",
    estimatedDuration: "less_than_1_month",
  },
  {
    id: 8,
    title: "social media app",
    description:
      "Build a scalable social media application with user profiles, posts, likes, comments, and real-time notifications.",
    budget: 1000,
    createdAt: "2026-03-25",
    status: "in_progress",
    proposalsCount: 3,
    experienceLevel: "senior",
    projectSize: "large",
    estimatedDuration: "more_than_6_months",
  },
];