import profile from "../assets/images/profile.png";

export const proposals = [
  // ===== project 1 (completed) =====
  {
    id: 1,
    projectId: 1,
    bid: 22,
    delivery: 10,
    coverLetter:
      "I have experience building e-commerce platforms with React and Node.js.",
    status: "accepted",
    createdAt: "2026-03-21T10:00:00Z",
    freelancer: {
      id: 101,
      name: "Ahmed Benali",
      title: "Full Stack Developer",
      avatar: profile,
      rating: 4.9,
    },
  },
  {
    id: 2,
    projectId: 1,
    bid: 18,
    delivery: 14,
    coverLetter: "I can deliver a responsive and scalable solution.",
    status: "rejected",
    createdAt: "2026-03-21T12:00:00Z",
    freelancer: {
      id: 102,
      name: "Sara El Idrissi",
      title: "Frontend Developer",
      avatar: profile,
      rating: 4.7,
    },
  },
  {
    id: 3,
    projectId: 1,
    bid: 25,
    delivery: 9,
    coverLetter: "I specialize in e-commerce UX and performance optimization.",
    status: "rejected",
    createdAt: "2026-03-21T15:00:00Z",
    freelancer: {
      id: 103,
      name: "Youssef Amrani",
      title: "UI/UX Engineer",
      avatar: profile,
      rating: 4.6,
    },
  },

  // ===== project 2 =====
  {
    id: 4,
    projectId: 2,
    bid: 15,
    delivery: 5,
    coverLetter: "I will build a modern and responsive restaurant UI.",
    status: "pending",
    createdAt: "2026-03-22T09:00:00Z",
    freelancer: {
      id: 104,
      name: "Omar Tazi",
      title: "Frontend Developer",
      avatar: profile,
      rating: 4.5,
    },
  },
  {
    id: 5,
    projectId: 2,
    bid: 17,
    delivery: 6,
    coverLetter: "Clean animations and mobile-first design guaranteed.",
    status: "pending",
    createdAt: "2026-03-22T11:00:00Z",
    freelancer: {
      id: 105,
      name: "Lina Berrada",
      title: "UI Designer",
      avatar: profile,
      rating: 4.8,
    },
  },

  // ===== project 3 =====
  {
    id: 6,
    projectId: 3,
    bid: 12,
    delivery: 4,
    coverLetter: "I have experience with REST APIs and caching.",
    status: "pending",
    createdAt: "2026-03-18T10:00:00Z",
    freelancer: {
      id: 106,
      name: "Hamza Naji",
      title: "Backend Developer",
      avatar: profile,
      rating: 4.7,
    },
  },
  {
    id: 7,
    projectId: 3,
    bid: 9,
    delivery: 5,
    coverLetter: "Lightweight and fast API implementation.",
    status: "pending",
    createdAt: "2026-03-18T12:00:00Z",
    freelancer: {
      id: 107,
      name: "Nadia Kabbaj",
      title: "Node.js Developer",
      avatar: profile,
      rating: 4.6,
    },
  },

  // ===== project 4 =====
  {
    id: 8,
    projectId: 4,
    bid: 28,
    delivery: 12,
    coverLetter: "Complete design system with Figma included.",
    status: "pending",
    createdAt: "2026-03-24T09:00:00Z",
    freelancer: {
      id: 108,
      name: "Imane Zahra",
      title: "UX Designer",
      avatar: profile,
      rating: 4.9,
    },
  },

  // ===== project 5 =====
  {
    id: 9,
    projectId: 5,
    bid: 23,
    delivery: 8,
    coverLetter: "Performance optimization and SEO improvements.",
    status: "pending",
    createdAt: "2026-03-23T10:00:00Z",
    freelancer: {
      id: 109,
      name: "Zakaria Fassi",
      title: "Full Stack Developer",
      avatar: profile,
      rating: 4.7,
    },
  },
  {
    id: 10,
    projectId: 5,
    bid: 26,
    delivery: 7,
    coverLetter: "Expert in improving e-commerce conversion rates.",
    status: "pending",
    createdAt: "2026-03-23T12:00:00Z",
    freelancer: {
      id: 110,
      name: "Salma Rami",
      title: "E-commerce Specialist",
      avatar: profile,
      rating: 4.8,
    },
  },

  // ===== project 7 =====
  {
    id: 11,
    projectId: 7,
    bid: 90,
    delivery: 6,
    coverLetter: "Modern portfolio with animations.",
    status: "rejected",
    createdAt: "2026-03-25T08:00:00Z",
    freelancer: {
      id: 111,
      name: "Yassine Chafai",
      title: "Frontend Developer",
      avatar: profile,
      rating: 4.6,
    },
  },

  // ===== project 8 =====
  {
    id: 12,
    projectId: 8,
    bid: 950,
    delivery: 40,
    coverLetter: "I can build scalable real-time apps.",
    status: "pending",
    createdAt: "2026-03-25T10:00:00Z",
    freelancer: {
      id: 112,
      name: "Rachid Ait Ali",
      title: "Backend Engineer",
      avatar: profile,
      rating: 4.9,
    },
  },
  {
    id: 13,
    projectId: 8,
    bid: 1100,
    delivery: 50,
    coverLetter: "Full social platform with WebSocket support.",
    status: "accepted",
    createdAt: "2026-03-25T12:00:00Z",
    freelancer: {
      id: 113,
      name: "Nasr Toumi",
      title: "Full Stack Developer",
      avatar: profile,
      rating: 4.8,
    },
  },
  {
    id: 14,
    projectId: 8,
    bid: 980,
    delivery: 45,
    coverLetter: "Clean architecture and scalable backend.",
    status: "accepted",
    createdAt: "2026-03-25T14:00:00Z",
    freelancer: {
      id: 114,
      name: "Karim Lahlou",
      title: "Software Engineer",
      avatar: profile,
      rating: 4.7,
    },
  },

  // ===== extra =====
  {
    id: 15,
    projectId: 5,
    bid: 32,
    delivery: 10,
    coverLetter: "Pixel-perfect UI/UX with accessibility focus.",
    status: "pending",
    createdAt: "2026-03-24T13:00:00Z",
    freelancer: {
      id: 115,
      name: "Meriem Saadi",
      title: "UI Designer",
      avatar: profile,
      rating: 4.8,
    },
  },
];
